apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: shop
  labels:
    app: payments
spec:
  # ClusterIP = internal only (DBs, caches, payment backends in real orgs).
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
